# fly.toml app configuration file generated for my-dad-rocks on 2024-01-11T19:33:44+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "my-dad-rocks"
primary_region = "ams"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
